### ISSUE TITLE
Make Disguises removable early

### ISSUE THREAD

**Issue by torrakkeres** [jsrn/MidnightWatch2020#28]

**Comment by torrakkeres** [comment]
Removing disguise kit does not clear NameMod property.

Removing disguise kit does not revert user's hairstyle. (Optional to fix. How does it regrow so fast?)

**Comment by jsrn** [comment]
I've sorted the name issue, but I can't replicate the hair bit.

![image](https://user-images.githubusercontent.com/1489178/80366037-7b0f1980-8880-11ea-8c48-f4c2ae0aa2db.png)

**Comment by torrakkeres** [comment]
All working fine. The fix did not apply retroactively to a character who had already used a disguise kit.
